export default actionConstants = {
  ADD_TODO_LIST: 'ADD_TODO_LIST',
  ADD_TODO_ITEM: 'ADD_TODO_ITEM',
  SET_MODAL_PROPERTIES: 'SET_MODAL_PROPERTIES',
  HANDLE_CHECKBOX: 'HANDLE_CHECKBOX',
  SET_SELECTED_LIST: 'SET_SELECTED_LIST',
};
