import {Dimensions} from 'react-native';

const {height, width} = Dimensions.get('window');
const helperSizes = {
  commonAppPadding: 15,
  lesserPadding: 10,
  addButtonSize: 20,
  addIconSize: 10,
  cardWidth: 200,
  cardHeight: 250,
  cardMargin: 20,
  addButtonRadius: 4,
  cardRadius: 10,
  widthShadowOffset: 10,
  heightShadowOffset: 10,
  cardShadowOpacity: 0.4,
  cardShadowRadius: 2,
  cardElevation: 1,
  cardLeftMargin: 10,
  checkBoxSize: 15,
  cardItemMarginTop: 10,
  modalOpacity: 0.4,
  inputHeight: 40,
  inputViewHeight: 300,
  height,
  width,
  clockEdge: 120,
  secHand: 50,
  minHand: 40,
  hourHand: 30,
  clockShadowWidth: 2,
  clockShadowHeight: 2,
  bigCardRadius: 30,
};
export default helperSizes;
